linters:
  disable-all: true
  enable:
    # Correctness
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style
    - gofmt
    - goimports
    - misspell

    # Safety
    - gosec
    - noctx
    - bodyclose

    # Maintainability
    - dupl
    - gocritic
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  gosec:
    excludes:
      - G304

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false

  dupl:
    threshold: 150

  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - dupl
        - gosec
    - path: "cmd/"
      linters:
        - revive
