name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug!

  - type: input
    id: version
    attributes:
      label: logr version
      description: Run `logr version` to find this
      placeholder: v0.1.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Log Source
      options:
        - Docker
        - Kubernetes
        - File
        - stdin
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `logr watch --docker`
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant output / error
      render: shell
